## Notebook de analise de metricas de saida dos modelos treinados

In [6]:
import pandas as pd
import sys
import numpy as np

In [18]:
## Read files 
df1_pred = np.load('../output/metricas/train/fold_0/predict_label_train_fold_0.npy')
df1_true = np.load('../output/metricas/train/fold_0/true_label_train_fold_0.npy')

In [21]:
df1_pred[0], df1_true[0]


(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 1, 1, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 1, 1, 1, 0],
        [1, 1, 0, 1, 1, 0, 1, 0, 0, 0],
        [1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 0, 1, 1, 1, 1, 1, 1],
        [0, 1, 0, 1, 1, 0, 0, 1, 1, 1],
        [1, 0, 1, 0, 0, 1, 0, 1, 0, 0]

In [20]:
pd.DataFrame([df1_pred[0], df1_true[0]], columns=['predicted_label', 'true_label'])

ValueError: Must pass 2-d input. shape=(2, 17, 10)

In [ ]:
## Create a dataframe for easier manipulation

df = pd.DataFrame(df1_pred[0], columns=['true_label', 'predicted_label'])

ValueError: Shape of passed values is (17, 10), indices imply (17, 2)

In [17]:
df1[0][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
## Create a dataframe for easier manipulation
df = pd.DataFrame(df1[0], columns=['true_label', 'predicted_label'])


ValueError: Shape of passed values is (17, 10), indices imply (17, 2)