## Notebook de analise de metricas de saida dos modelos treinados

In [5]:
!pip install pandas numpy matplotlib seaborn scikit-learn torch -q


[notice] A new release of pip is available: 25.1.1 -> 26.0
[notice] To update, run: pip install --upgrade pip


In [1]:
import pandas as pd
import sys
import numpy as np
import torch
from torch import nn

In [2]:
## Read files 
df1_pred = np.load('../output/metricas/train/fold_0/predict_label_train_fold_0.npy')
df1_true = np.load('../output/metricas/train/fold_0/true_label_train_fold_0.npy')

In [7]:
df1_true

array([[[1, 1, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [1, 0, 0, ..., 0, 0, 1],
        ...,
        [0, 1, 1, ..., 1, 1, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 1, 0]],

       [[1, 0, 0, ..., 0, 1, 0],
        [1, 0, 1, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        ...,
        [0, 0, 1, ..., 0, 1, 1],
        [1, 1, 1, ..., 1, 1, 0],
        [0, 1, 1, ..., 0, 1, 1]],

       [[1, 0, 1, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 1],
        [0, 1, 1, ..., 1, 0, 0],
        ...,
        [1, 1, 0, ..., 1, 0, 1],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 1, 1, ..., 1, 0, 1]],

       ...,

       [[0, 0, 1, ..., 0, 1, 0],
        [0, 1, 1, ..., 1, 1, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 0, ..., 0, 0, 0],
        [0, 1, 1, ..., 1, 1, 1],
        [1, 0, 1, ..., 0, 0, 1]],

       [[0, 1, 0, ..., 1, 0, 0],
        [1, 0, 1, ..., 1, 1, 1],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 1, ..., 

In [ ]:
def plot_train_test_loss(outputs, labels):
    criterio = nn.BCEWithLogitsLoss()
    import matplotlib.pyplot as plt
    acc = []
    for i in range(40):
        #print(f'Size of output {i}: {outputs[i].shape}, Size of label {i}: {labels[i].shape}')
        loss = criterio(outputs[i], labels[i])
        acc.append(loss.item())
        #print(f'Loss for sample {i}: {loss.item()}')
    plt.plot(acc)
    plt.title('Train Loss over Samples')
    plt.xlabel('Sample Index')
    plt.ylabel('Loss')
    plt.show()


In [6]:
criterio = nn.BCEWithLogitsLoss()

for i in range(len(df1_pred)):
    outputs_tensor = torch.tensor(df1_pred[i]).to(torch.float)
    labels_tensor = torch.tensor(df1_true[i]).to(torch.float)
    print(outputs_tensor.shape, labels_tensor.shape)
    plot_train_test_loss(outputs_tensor, labels_tensor)
    loss = criterio(outputs_tensor, labels_tensor)
    print(f'Loss for batch {i}: {loss.item()}')


torch.Size([40, 15]) torch.Size([40, 15])


IndexError: index 40 is out of bounds for dimension 0 with size 40

In [8]:
## Calculo precisao, recall e f1 score
from sklearn.metrics import precision_score, recall_score, f1_score
for i in range(len(df1_pred)):
    outputs_tensor = torch.tensor(df1_pred[i]).to(torch.float)
    labels_tensor = torch.tensor(df1_true[i]).to(torch.float)
    
    # Convertir las predicciones a etiquetas binarias (0 o 1) usando un umbral de 0.5
    predicted_labels = (outputs_tensor > 0.5).int().numpy()
    true_labels = labels_tensor.int().numpy()
    
    precision = precision_score(true_labels, predicted_labels, average='micro')
    recall = recall_score(true_labels, predicted_labels, average='micro')
    f1 = f1_score(true_labels, predicted_labels, average='micro')
    

/home/leo/Documents/dev/oca-ia/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [31]:
m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, 2, requires_grad=True)
target = torch.rand(3, 2, requires_grad=False)
output = loss(m(input), target)
output

tensor(0.6661, grad_fn=<BinaryCrossEntropyBackward0>)

In [32]:
loss2 = nn.BCEWithLogitsLoss()
output2 = loss2(input, target)
output2

tensor(0.6661, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [21]:
input

tensor([[ 0.0239,  0.5421],
        [-1.8023, -0.0728],
        [ 0.4282, -0.2552]], requires_grad=True)

In [22]:
target

tensor([[0.5561, 0.8056],
        [0.9565, 0.7501],
        [0.6653, 0.2292]])

In [29]:
loss2 = nn.BCEWithLogitsLoss()
output2 = loss2(input, target)
output2

tensor(0.5714, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)